import type { Metadata } from 'next';
import './globals.css';
import { mulish } from './fonts';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-background antialiased ${mulish.className}`}>
        <div className=" flex min-h-screen w-full flex-col bg-background">{children}</div>
      </body>
    </html>
  );
}
