const CountryCode = [
  { code: "AD", name: "Andorra", flag: "🇦🇩", phoneCode: "+376" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", phoneCode: "+971" },
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", phoneCode: "+93" },
  { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", phoneCode: "+1" },
  { code: "AI", name: "Anguilla", flag: "🇦🇮", phoneCode: "+1" },
  { code: "AL", name: "Albania", flag: "🇦🇱", phoneCode: "+355" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", phoneCode: "+374" },
  { code: "AO", name: "Angola", flag: "🇦🇴", phoneCode: "+244" },
  { code: "AQ", name: "Antarctica", flag: "🇦🇶", phoneCode: "+672" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", phoneCode: "+54" },
  { code: "AS", name: "American Samoa", flag: "🇦🇸", phoneCode: "+1" },
  { code: "AT", name: "Austria", flag: "🇦🇹", phoneCode: "+43" },
  { code: "AU", name: "Australia", flag: "🇦🇺", phoneCode: "+61" },
  { code: "AW", name: "Aruba", flag: "🇦🇼", phoneCode: "+297" },
  { code: "AX", name: "Åland Islands", flag: "🇦🇽", phoneCode: "+358" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", phoneCode: "+994" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", phoneCode: "+387" },
  { code: "BB", name: "Barbados", flag: "🇧🇧", phoneCode: "+1" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", phoneCode: "+880" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", phoneCode: "+32" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", phoneCode: "+226" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", phoneCode: "+359" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", phoneCode: "+973" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", phoneCode: "+257" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", phoneCode: "+229" },
  { code: "BL", name: "Saint Barthélemy", flag: "🇧🇱", phoneCode: "+590" },
  { code: "BM", name: "Bermuda", flag: "🇧🇲", phoneCode: "+1" },
  { code: "BN", name: "Brunei Darussalam", flag: "🇧🇳", phoneCode: "+673" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", phoneCode: "+591" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", flag: "🇧🇶", phoneCode: "+599" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", phoneCode: "+55" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", phoneCode: "+1" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", phoneCode: "+975" },
  { code: "BV", name: "Bouvet Island", flag: "🇧🇻", phoneCode: "+47" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", phoneCode: "+267" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", phoneCode: "+375" },
  { code: "BZ", name: "Belize", flag: "🇧🇿", phoneCode: "+501" },
  { code: "CA", name: "Canada", flag: "🇨🇦", phoneCode: "+1" },
  { code: "CC", name: "Cocos (Keeling) Islands", flag: "🇨🇨", phoneCode: "+61" },
  { code: "CD", name: "Congo, Democratic Republic", flag: "🇨🇩", phoneCode: "+243" },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫", phoneCode: "+236" },
  { code: "CG", name: "Congo", flag: "🇨🇬", phoneCode: "+242" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", phoneCode: "+41" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", phoneCode: "+225" },
  { code: "CK", name: "Cook Islands", flag: "🇨🇰", phoneCode: "+682" },
  { code: "CL", name: "Chile", flag: "🇨🇱", phoneCode: "+56" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", phoneCode: "+237" },
  { code: "CN", name: "China", flag: "🇨🇳", phoneCode: "+86" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", phoneCode: "+57" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", phoneCode: "+506" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", phoneCode: "+53" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻", phoneCode: "+238" },
  { code: "CW", name: "Curaçao", flag: "🇨🇼", phoneCode: "+599" },
  { code: "CX", name: "Christmas Island", flag: "🇨🇽", phoneCode: "+61" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", phoneCode: "+357" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿", phoneCode: "+420" },
  { code: "DE", name: "Germany", flag: "🇩🇪", phoneCode: "+49" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", phoneCode: "+253" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", phoneCode: "+45" },
  { code: "DM", name: "Dominica", flag: "🇩🇲", phoneCode: "+1" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", phoneCode: "+1" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", phoneCode: "+213" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", phoneCode: "+593" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", phoneCode: "+372" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", phoneCode: "+20" },
  { code: "EH", name: "Western Sahara", flag: "🇪🇭", phoneCode: "+212" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", phoneCode: "+291" },
  { code: "ES", name: "Spain", flag: "🇪🇸", phoneCode: "+34" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", phoneCode: "+251" },
  { code: "FI", name: "Finland", flag: "🇫🇮", phoneCode: "+358" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", phoneCode: "+679" },
  { code: "FK", name: "Falkland Islands", flag: "🇫🇰", phoneCode: "+500" },
  { code: "FM", name: "Micronesia", flag: "🇫🇲", phoneCode: "+691" },
  { code: "FO", name: "Faroe Islands", flag: "🇫🇴", phoneCode: "+298" },
  { code: "FR", name: "France", flag: "🇫🇷", phoneCode: "+33" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", phoneCode: "+241" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", phoneCode: "+44" },
  { code: "GD", name: "Grenada", flag: "🇬🇩", phoneCode: "+1" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", phoneCode: "+995" },
  { code: "GF", name: "French Guiana", flag: "🇬🇫", phoneCode: "+594" },
  { code: "GG", name: "Guernsey", flag: "🇬🇬", phoneCode: "+44" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", phoneCode: "+233" },
  { code: "GI", name: "Gibraltar", flag: "🇬🇮", phoneCode: "+350" },
  { code: "GL", name: "Greenland", flag: "🇬🇱", phoneCode: "+299" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", phoneCode: "+220" },
  { code: "GN", name: "Guinea", flag: "🇬🇳", phoneCode: "+224" },
  { code: "GP", name: "Guadeloupe", flag: "🇬🇵", phoneCode: "+590" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", phoneCode: "+240" },
  { code: "GR", name: "Greece", flag: "🇬🇷", phoneCode: "+30" },
  { code: "GS", name: "South Georgia", flag: "🇬🇸", phoneCode: "+500" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", phoneCode: "+502" },
  { code: "GU", name: "Guam", flag: "🇬🇺", phoneCode: "+1-671" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", phoneCode: "+245" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", phoneCode: "+592" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", phoneCode: "+852" },
  { code: "HM", name: "Heard Island and McDonald Islands", flag: "🇭🇲", phoneCode: "" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", phoneCode: "+504" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", phoneCode: "+385" },
  { code: "HT", name: "Haiti", flag: "🇭🇹", phoneCode: "+509" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", phoneCode: "+36" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", phoneCode: "+62" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", phoneCode: "+353" },
  { code: "IL", name: "Israel", flag: "🇮🇱", phoneCode: "+972" },
  { code: "IM", name: "Isle of Man", flag: "🇮🇲", phoneCode: "+44" },
  { code: "IN", name: "India", flag: "🇮🇳", phoneCode: "+91" },
  { code: "IO", name: "British Indian Ocean Territory", flag: "🇮🇴", phoneCode: "+246" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", phoneCode: "+964" },
  { code: "IR", name: "Iran, Islamic Republic of", flag: "🇮🇷", phoneCode: "+98" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", phoneCode: "+354" },
  { code: "IT", name: "Italy", flag: "🇮🇹", phoneCode: "+39" },
  { code: "JE", name: "Jersey", flag: "🇯🇪", phoneCode: "+44" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", phoneCode: "+1-876" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", phoneCode: "+962" },
  { code: "JP", name: "Japan", flag: "🇯🇵", phoneCode: "+81" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", phoneCode: "+254" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", phoneCode: "+7" },
  { code: "LA", name: "Lao People's Democratic Republic", flag: "🇱🇦", phoneCode: "+856" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", phoneCode: "+961" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨", phoneCode: "+1-758" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", phoneCode: "+423" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", phoneCode: "+94" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", phoneCode: "+231" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", phoneCode: "+266" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", phoneCode: "+370" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", phoneCode: "+352" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", phoneCode: "+371" },
  { code: "LY", name: "Libya", flag: "🇱🇾", phoneCode: "+218" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", phoneCode: "+212" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", phoneCode: "+377" },
  { code: "MD", name: "Moldova, Republic of", flag: "🇲🇩", phoneCode: "+373" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", phoneCode: "+382" },
  { code: "MF", name: "Saint Martin", flag: "🇲🇫", phoneCode: "+590" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", phoneCode: "+261" },
  { code: "MH", name: "Marshall Islands", flag: "🇲🇭", phoneCode: "+692" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰", phoneCode: "+389" },
  { code: "ML", name: "Mali", flag: "🇲🇱", phoneCode: "+223" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", phoneCode: "+95" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", phoneCode: "+976" },
  { code: "MO", name: "Macao", flag: "🇲🇴", phoneCode: "+853" },
  { code: "MP", name: "Northern Mariana Islands", flag: "🇲🇵", phoneCode: "+1-670" },
  { code: "MQ", name: "Martinique", flag: "🇲🇶", phoneCode: "+596" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", phoneCode: "+222" },
  { code: "MS", name: "Montserrat", flag: "🇲🇸", phoneCode: "+1-664" },
  { code: "MT", name: "Malta", flag: "🇲🇹", phoneCode: "+356" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", phoneCode: "+230" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", phoneCode: "+960" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", phoneCode: "+265" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", phoneCode: "+52" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", phoneCode: "+60" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", phoneCode: "+258" },
  { code: "NA", name: "Namibia", flag: "🇳🇦", phoneCode: "+264" },
  { code: "NC", name: "New Caledonia", flag: "🇳🇨", phoneCode: "+687" },
  { code: "NE", name: "Niger", flag: "🇳🇪", phoneCode: "+227" },
  { code: "NF", name: "Norfolk Island", flag: "🇳🇫", phoneCode: "+672" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", phoneCode: "+234" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", phoneCode: "+505" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", phoneCode: "+31" },
  { code: "NO", name: "Norway", flag: "🇳🇴", phoneCode: "+47" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", phoneCode: "+977" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", phoneCode: "+674" },
  { code: "NU", name: "Niue", flag: "🇳🇺", phoneCode: "+683" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", phoneCode: "+64" },
  { code: "OM", name: "Oman", flag: "🇴🇲", phoneCode: "+968" },
  { code: "PA", name: "Panama", flag: "🇵🇦", phoneCode: "+507" },
  { code: "PE", name: "Peru", flag: "🇵🇪", phoneCode: "+51" },
  { code: "PF", name: "French Polynesia", flag: "🇵🇫", phoneCode: "+689" },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", phoneCode: "+675" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", phoneCode: "+63" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", phoneCode: "+92" },
  { code: "PL", name: "Poland", flag: "🇵🇱", phoneCode: "+48" },
  { code: "PM", name: "Saint Pierre and Miquelon", flag: "🇵🇲", phoneCode: "+508" },
  { code: "PN", name: "Pitcairn", flag: "🇵🇳", phoneCode: "+870" },
  { code: "PR", name: "Puerto Rico", flag: "🇵🇷", phoneCode: "+1-787", phoneCodeAlt: "+1-939" },
  { code: "PS", name: "Palestine, State of", flag: "🇵🇸", phoneCode: "+970" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", phoneCode: "+351" },
  { code: "PW", name: "Palau", flag: "🇵🇼", phoneCode: "+680" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", phoneCode: "+595" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", phoneCode: "+974" },
  { code: "RE", name: "Réunion", flag: "🇷🇪", phoneCode: "+262" },
  { code: "RO", name: "Romania", flag: "🇷🇴", phoneCode: "+40" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", phoneCode: "+381" },
  { code: "RU", name: "Russian Federation", flag: "🇷🇺", phoneCode: "+7" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", phoneCode: "+250" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", phoneCode: "+966" },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧", phoneCode: "+677" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", phoneCode: "+248" },
  { code: "SD", name: "Sudan", flag: "🇸🇩", phoneCode: "+249" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", phoneCode: "+46" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", phoneCode: "+65" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", flag: "🇸🇭", phoneCode: "+290" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", phoneCode: "+386" },
  { code: "SJ", name: "Svalbard and Jan Mayen", flag: "🇸🇯", phoneCode: "+47" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", phoneCode: "+421" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", phoneCode: "+232" },
  { code: "SM", name: "San Marino", flag: "🇸🇲", phoneCode: "+378" },
  { code: "SN", name: "Senegal", flag: "🇸🇳", phoneCode: "+221" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", phoneCode: "+252" },
  { code: "SR", name: "Suriname", flag: "🇸🇷", phoneCode: "+597" },
  { code: "SS", name: "South Sudan", flag: "🇸🇸", phoneCode: "+211" },
  { code: "ST", name: "Sao Tome and Principe", flag: "🇸🇹", phoneCode: "+239" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", phoneCode: "+503" },
  { code: "SX", name: "Sint Maarten, Dutch part", flag: "🇸🇽", phoneCode: "+1-721" },
  { code: "SY", name: "Syrian Arab Republic", flag: "🇸🇾", phoneCode: "+963" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", phoneCode: "+268" },
  { code: "TC", name: "Turks and Caicos Islands", flag: "🇹🇨", phoneCode: "+1-649" },
  { code: "TD", name: "Chad", flag: "🇹🇩", phoneCode: "+235" },
  { code: "TF", name: "French Southern Territories", flag: "🇹🇫", phoneCode: "+262" },
  { code: "TG", name: "Togo", flag: "🇹🇬", phoneCode: "+228" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", phoneCode: "+66" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", phoneCode: "+992" },
  { code: "TK", name: "Tokelau", flag: "🇹🇰", phoneCode: "+690" },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱", phoneCode: "+670" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", phoneCode: "+993" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", phoneCode: "+216" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", phoneCode: "+676" },
  { code: "TR", name: "Türkiye", flag: "🇹🇷", phoneCode: "+90" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", phoneCode: "+1-868" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", phoneCode: "+688" },
  { code: "TW", name: "Taiwan, Province of China", flag: "🇹🇼", phoneCode: "+886" },
  { code: "TZ", name: "Tanzania, United Republic of", flag: "🇹🇿", phoneCode: "+255" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", phoneCode: "+380" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", phoneCode: "+256" },
  { code: "UM", name: "United States Minor Outlying Islands", flag: "🇺🇲", phoneCode: "" },
  { code: "US", name: "United States of America", flag: "🇺🇸", phoneCode: "+1" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", phoneCode: "+598" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", phoneCode: "+998" },
  { code: "VA", name: "Holy See (Vatican City State)", flag: "🇻🇦", phoneCode: "+379" },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", phoneCode: "+1-784" },
  { code: "VE", name: "Venezuela, Bolivarian Republic of", flag: "🇻🇪", phoneCode: "+58" },
  { code: "VG", name: "Virgin Islands, British", flag: "🇻🇬", phoneCode: "+1-284" },
  { code: "VI", name: "Virgin Islands, U.S.", flag: "🇻🇮", phoneCode: "+1-340" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", phoneCode: "+84" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", phoneCode: "+678" },
  { code: "WF", name: "Wallis and Futuna", flag: "🇼🇫", phoneCode: "+681" },
  { code: "WS", name: "Samoa", flag: "🇼🇸", phoneCode: "+685" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", phoneCode: "+967" },
  { code: "YT", name: "Mayotte", flag: "🇾🇹", phoneCode: "+262" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", phoneCode: "+27" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", phoneCode: "+260" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", phoneCode: "+263" },
];

export default CountryCode